export const annexes = [
  "Annex 1 PERSONNEL LICENSING",
  "Annex 2 RULES OF THE AIR",
  "Annex 3 METEOROLOGICAL SERVICE FOR INTERNATIONAL AIR NAVIGATION PART I - CORE SARPs",
  "Annex 4 AERONAUTICAL CHARTS",
  "Annex 5 UNITS OF MEASUREMENT TO BE USED IN AIR AND GROUND OPERATIONS",
  "Annex 6 OPERATION OF AIRCRAFT PART I INTERNATIONAL COMMERICIAL AIR TRANSPORT - AEROPLANES",
  "Annex 6 OPERATION OF AIRCRAFT PART II INTERNATIONAL GENERAL AVIATION - AEROPLANES",
  "Annex 6 OPERATION OF AIRCRAFT PART III INTERNATIONAL OPERATIONS - HELICOPTERS",
  "Annex 6 OPERATION OF AIRCRAFT PART IV - International Operations - Remotely Piloted Aircraft Systems",
  "Annex 7 AIRCRAFT NATIONALITY AND REGISTRATION MARKS",
  "Annex 8 AIRWORTHINESS OF AIRCRAFT",
  "Annex 9 FACILITATION",
  "Annex 10 AERONAUTICAL TELECOMMUNICATIONS VOLUME I RADIO NAVIGATION AIDS",
  "Annex 10 AERONAUTICAL TELECOMMUNICATIONS VOLUME II COMMUNICATION PROCEDURES INCLUDING THOSE WITH PANS STATUS",
  "Annex 10 AERONAUTICAL TELECOMMUNICATIONS VOLUME III PART I - DIGITAL DATA COMMUNICATION SYSTEMS; PART II - VOICE COMMUNICATION SYSTEMS",
  "Annex 10 AERONAUTICAL TELECOMMUNICATIONS VOLUME IV SURVEILLANCE RADAR AND COLLISION AVOIDANCE SYSTEMS",
  "Annex 10 AERONAUTICAL TELECOMMUNICATIONS VOLUME V AERONAUTICAL RADIO FREQUENCY SPECTRUM UTILIZATION",
];

export const ancProgresBarContents = [
  {
    index: 1,
    content: "Document Type",
  },
  {
    index: 2,
    content: "Select Annex",
  },
  {
    index: 3,
    content: "Annex Version",
  },
  {
    index: 4,
    content: "Document Type",
  },
  {
    index: 5,
    content: "Annex Section",
  },
  {
    index: 6,
    content: "Confirm",
  },
];
